// <auto-generated />
using CHMM.DataImport.Logic.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHMM.DataImport.Logic.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CHMM.DataImport.Logic.Models.RootEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("text");

                    b.Property<string>("AlternativeHeatingSystemDescription")
                        .HasColumnType("text");

                    b.Property<string>("AlternativeHeatingSystemFuelDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AlternativeHeatingSystemFuelID")
                        .HasColumnType("integer");

                    b.Property<int>("AlternativeHeatingSystemID")
                        .HasColumnType("integer");

                    b.Property<string>("CommissioningDate")
                        .HasColumnType("text");

                    b.Property<double>("CostOfInstallation")
                        .HasColumnType("double precision");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<int>("InstallerMCSID")
                        .HasColumnType("integer");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("SystemDesignedToProvideDescription")
                        .HasColumnType("text");

                    b.Property<int>("SystemDesignedToProvideID")
                        .HasColumnType("integer");

                    b.Property<double>("TotalInstallationCapacity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
